# Generated by Django 5.2.1 on 2025-06-15 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leetcode_tracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=100)),
            ],
        ),
    ]
