# Generated by Django 5.2.1 on 2025-06-17 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leetcode_tracker', '0002_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
